"""shop website api key

Revision ID: 5283eb35d801
Revises: b8e6efe71c43
Create Date: 2026-06-17 09:15:52.128343

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5283eb35d801'
down_revision: str | Sequence[str] | None = 'b8e6efe71c43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('api_key_encrypted', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('api_key_prefix', sa.String(length=8), nullable=True))
        batch_op.create_index(batch_op.f('ix_shops_api_key_prefix'), ['api_key_prefix'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_api_key_prefix'))
        batch_op.drop_column('api_key_prefix')
        batch_op.drop_column('api_key_encrypted')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
