"""shop webhook

Revision ID: e7f4db7e4cdc
Revises: 5283eb35d801
Create Date: 2026-06-17 10:04:03.479572

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e7f4db7e4cdc'
down_revision: str | Sequence[str] | None = '5283eb35d801'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('webhook_secret_encrypted', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('webhook_secret_encrypted')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
